spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.103.64.74:3306/mosidian_pro?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: mosidian
      password: 2020mosiDian@
      #            url: jdbc:mysql://192.168.200.106:3306/jxmall_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      #            username: root
      #            password: 131013
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  rabbitmq:
      addresses: www.mosidian.com
      port: 5672
      username: admin
      password: admin

  freemarker:
    suffix: .ftl

alipay:
  appId: 2016101800717551
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC1ksxzzurGrS/jLdrJSXyohyoUk+rRlhowD0qp+RDfl5j9qBHC3udhKDLUFNgxLNgdku1J5tjPW5JTLetM8vBHXsgNj4gR/ERBid7LJuJWn081LxyBEAigNKWBfBS7Y0GJ19IGV2nBxZrfxVTYWjPZB5N+fXTxAEVwXyezKu16TsyLlZ+YpelDOkdHlJY3tfhTpWpOdZLD6eCTavhJrD3uqSGy3UY6SEOZAbAK71wB195v3CNnEurdJaRyezyKvbmY3oLQMz7xWeavAptKFQUTQ+aV7ezACzgG9EACRtaxmwGvGzjaS1yeChAqa6HIBNDwB+p4IHGNymlMysYC7urfAgMBAAECggEAKwbQYBkGVXIwyNrS36QEYEM3W4z5thSlvAHDpaeZsgJQhLtRCiacGc/Wy57s5CpGRCvPAxYrBmgisodNHPzsp1z0dxIuImTvH8C2BNoABJrXwDibvpG4GY6gMaDfoNASdcGoyUvpibtzydcPFf26D5HWB8Fe9sUjr089Lx3bDII8nnUBDtBmg9InplCglFD4lEUwurxluRgcY+mkGKojuTLrk61Zbhz/d2nmOm6A6AHTuORD9BgN+wso2gpeiAxTICMBUuC680lKaW+YfIDCfARG3xOIwC1rO4aklR1JGh//3ewTHwB7cfwHqV2FQMEC7h4VvLsXMpgLWgIhO5UosQKBgQD3Pa45l8hKc32Awlgn6slvDTDywuKWmkbHPObqryEdjlcLo9fMKeLMlMS/WuJhqxQZuq30gXgIz/NZL+6N1BtfBkElVzGxGGujRPLjNEHDtzXLBAy3QXv6RE4CFb6LDWL8FQcJfPu4arn4hPRkE463G39/bQeKjh2fGhy2T9OIrQKBgQC8AY4gvVrxyha43SAYogXfzAORB/IO9onraZqi6anyEQVbFbLfYovyLg1wRSepB8Kec9ZO77F3FXPnJeE8s561OnR1zimlhLmvAucrTvBiFZ84XKl2UKonOjHta0PqVA3r2tRwl2AE9IRBGQAuiPBJhFY+GApMajVhBxqsAf53OwKBgESR1sAiWGpNnYEYZVqswzEJd4ncgvtBzl9zhJeR+p033OxdhHwbIcubdvWbPy3XRLveCmDFh4TqJ5OUt5SePvkbwvWYOS/klfWyKarZ02N0bHbhqKUqhDfkub3aSf5GuC0xp8H559Y9w1YpiZ43zlz6Q2IT2wOSZqS5mTz25rQBAoGBALh3Uivffw9EeRzzoh1pRBg9BbbUs/VogxSfrmFwoRXpC3c+iB5Ug/mgpADnaa2Y9qUgBUO4PUkZnHpNGX3Ew9EPxNsd6JEF9Ga6k3VT49ppWqsjiAaVyQ3qNLi+CYou5OXo9Y5viH/0Jpv02s/N/u4zUadlUR1/DFbicJIa9sGnAoGBALf7dnzUeZGA9V1EJvt4Pv1WW+USPdccFZtmblEyV79suzav6kZwq12oKbMCHZjXbiSHivlfPGmXPaJm4QqRCDJ/0HKlFKcMDPF4+OD2lNlHzQf9Ol913WPnj4le7V8iNA9bwVDPDmzRFGr3k6+HRO2SfHweZLKwT4mxqNmCKLiM
  aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhnq4jj3RkgYxzbXkjMtMVB+vJTi0mIOzb1FlajkrYwBygsNc8c4sjztDwfVLLG52IXqtC+ZM4MPSnILX8JBl543POhV3G4F+mP6YjZlrOuStX0if/a2h5esBSHM+e1hbZJUESGfNFsCuXyjkjC2JRji2VFuDolXnfIBthOEmt5aWJJOCyZBkEDYjrgJeA/wz8Bzr9tPvasV7hzC2kTJmL50ghxhKNtgS56Gu38TYGQFgiZEoNMPbOa9/W57iwvqSg2fNTpU2f9YO82oUUmtyibHTJ8lik8pP5gspLG2g4wyScJtpcIzAQoG7J6vrJQYQ8xzbkZaFGO8AeP6EMf466QIDAQAB
#  notifyUrl: http://samphanie.natapp1.cc/pay/notify
  notifyUrl: http://www.mosidian.com/pay/notify
  returnUrl: http://www.mosidian.com/mosidian-admin/#/home
  sandbox: true #是否使用沙箱

wechat:
  mpAppId: wxf575fcff4fd8fddd
  mpAppSecret: 2fbd350c071d6fae7a0cb193b6594d1e
  mchId:
  mchKey:
  keyPath:
  notifyUrl: http://www.mosidian.com/pay/notify

##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=mosidian_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/mosidian_security
#      username: mosidian
#      password: 123456